import React, { HTMLProps, ReactNode } from 'react';
import Head from 'next/head';
import Header from '../layout/header';

interface LayoutProps extends HTMLProps<HTMLDivElement> {
  children: ReactNode;
  title: string;
}

const Layout = ({
  children,
  title,
}: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{`${title} | Player Value`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {children}
    </>
  );
};

export default Layout;
